### ISSUE TITLE
missing net/wireguard/Kconfig 

### ISSUE THREAD

**Issue by dwdvIl** [ananjaser1211/Helios_7870#9]
build_kernel.sh
net/Kconfig:80: can't open file "net/wireguard/Kconfig"
make[1]: *** [scripts/kconfig/Makefile:105: exynos7870-a6lte_defconfig] Error 1
make: *** [Makefile:569: exynos7870-a6lte_defconfig] Error 2
scripts/kconfig/conf --silentoldconfig Kconfig
net/Kconfig:80: can't open file "net/wireguard/Kconfig"
make[2]: *** [scripts/kconfig/Makefile:37: silentoldconfig] Error 1
make[1]: *** [Makefile:569: silentoldconfig] Error 2

I checked the directory and there is no such folder and file, i tried to skip that line in net/Kconfig but it cannot continue

**Comment by dwdvIl** [comment]
Anyways i only want to enable KVM on the kernel, idk if there is another method, but this seems the only one

**Comment by ananjaser1211** [comment]
The wireguard importer script might be outdated.
Disable wireguard in config or take the updated importer from my cronos_8890 kernel. I do not maintain anything 7870 wise

**Comment by dwdvIl** [comment]
Cant you only send me the Kconfig file? Still doesnt working, and you didnt give me full details and already closing the thread? What kind of help is this?

**Comment by ananjaser1211** [comment]
> Cant you only send me the Kconfig file? Still doesnt working, and you didnt give me full details and already closing the thread? What kind of help is this?

There is another closed issue regarding the same topic with the updated wireguard sh. You can't just add the kconfig. The importer downloads the wireguard driver (so it's latest Everytime) into net. 

https://github.com/ananjaser1211/Helios_7870/commit/100b0d2603e247b14dc04adb1c0174be3f4ffaf4

The script was updated in the "Cronos" branch. Which is the last thing I worked on. All other branches are for oreo and outdated pie releases.

Finally. Use cronos.sh to compile, there are alot of hacks in this kernel and split file configs that will be merged together.

And there are 30 forks of this kernel you can follow. I no longer support or work on this platform since 7 months. Hence why I closed it. 

If you want an updated version follow Ares (formerly known as kraken)

Edit : also this is the script I mentioned to use btw https://github.com/ananjaser1211/Cronos_8890/blob/cronos/scripts/fetch-latest-wireguard.sh

**Comment by dwdvIl** [comment]
bash fetch-wireguard.sh
Error:
not a valid option: line 2: set: -
(Shows usage of set)
fetch-wireguard.sh: line 12: syntax error near element `done'

'etch-wireguard.sh: line 12: `done < <(curl -A "$USER_AGENT" -LSs --connect-timeout 30 https://build.wireguard.com/distros.txt)

There were '\r' spaces error but i just deleted it in the file

**Comment by dwdvIl** [comment]
Ok, like almost all of my projects, i figured out by myself and now is working. But thanks for providing details, this is the properly way to close a thread.
